import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/common/Navbar";
import { Toaster } from 'react-hot-toast';
import AuthProvider from "./contaxt/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider > 
          <div className = "xl:container mx-auto">
              <Navbar/>
              {children}
          </div>
          </AuthProvider>
          <Toaster />

      </body>
    </html>
  );
}
